### ISSUE TITLE
Question from Nikhef

### ISSUE THREAD

**Issue by DamunCow** [argus-authz/load-testsuite#4]
Hello, 

I'm currently busy with the Argus Framework for the Nikhef. The test here on github are not compatible with The grinder 3.11. Out of curiosity I have a question.  Are you guys busy with updating the test to be compatible with the Grinder?

**Comment by andreaceccanti** [comment]
What are the issues you're facing?
The load testsuite is supposed to be Grinder-3.11 compliant.

**Comment by DamunCow** [comment]
Ah! I made an error, turns out the test does run on a CentOS 7 machine. I locally use debian 8, it was my inexpirience that did not notice that a package was missing. My bad!

**Comment by andreaceccanti** [comment]
ok. closing the issue then.
